### ISSUE TITLE
Add appVeyor builds

### ISSUE THREAD

**Issue by Brett208** [OutpostUniverse/op2ext#10]
x86 debug and release would be appropriate as it should never be required to complete an x64 build.

**Comment by Brett208** [comment]
I have appveyor working in a branch. The branch contains lots of conflicting commits as I had to push often to test. Would like to create a new branch and add appveyor in a single commit or squash the commits in the currently public branch.

Then probably merge the master back into the current open branch on the logger.

-Brett

**Comment by DanRStevens** [comment]
Yes, you would be correct about not needing an x64 build.

You can use an interactive re-base to cleanup your branch, or even rebase it on top of a current master in case it was based on a new stale version. The interactive rebase would give you precise control over the ordering of commits, and which commits should be squashed with each other.

In terms of getting CI builds working, which often needs a lot of experimental commits, I often just use `--amend` to fixup my last commit, and then force push after each change. This means I rewrite history as I work, rather than trying to clean it all up at the end. The end result is the same though, in that it keeps commit noise down to a minimum.

**Comment by Brett208** [comment]
I just tried ammend for the first time. Straight forward to use. Thanks for the tip on it. Closing this issue now that appveyor is working. There are other things I could use help on in general if we are itching to do another pair programming round.

-Brett
