### ISSUE TITLE
Switch TestModule from reporting in output window to using logger

### ISSUE THREAD

**Issue by Brett208** [OutpostUniverse/op2ext#137]
Currently the TestModule reports successful calling of different functions across DLL boundaries via the IDE's output window. That output is mixed with a bunch of other messages. 

I think it would be better behaviour to log the TestModule's finding with the logger for easier location and to exercise the logger itself.

**Comment by DanRStevens** [comment]
To test being loaded by op2ext? Perhaps yes.

----

I still think there's a better way to test the op2ext DLL interface itself. From that perspective, it's a library like any other. Some code gets a reference to it, and calls methods from it. To test the DLL interface, we could write a test EXE that loads op2ext.dll and calls the exported methods. That would be like running a regular Google Test unit test, which we could use for the output and error reporting.

One slight complication is that when op2ext.dll loads, it tries to patch Outpost2.exe. We would probably need to load Outpost2.exe and then op2ext.dll from such a test executable. Which is easy enough to do.

I think this would actually cover the majority of our testing needs, and would be the easier to work with.

**Comment by DanRStevens** [comment]
I gave my idea a bit of a try by slapping a `WinMain` function on the TestModule project, and compiling it as an EXE. Unfortunately it wasn't quite so easy to do what I wanted.

The test exe was loading op2ext.dll, and I was getting error message popups from it. However, the error message popups were because it was failing to patch Outpost2.exe code, because that module wasn't loaded by the OS. I tried putting in a `LoadLibrary` call, but still to the same effect.

It occurred to me that was because the op2ext.dll links were all eager references, and so it was loaded first during initialization. Meanwhile I was trying to use a delayed dynamic load using `LoadLibrary` to load Outpost2.exe, which happens after `WinMain` starts. Effectively it was loading op2ext.dll first, and running its `DllMain` before I hit the `LoadLibrary` call for Outpost2.exe. This was a problem since the `DllMain` from op2ext contains a patch call for Outpost2.exe, and if it reports failure, the DLL returns `FALSE` from `DllMain`. That signals to the OS loader that the DLL failed to initialize, and it aborts loading it. As the test executable has a hard set requirement to use op2ext.dll, that causes the test executable to abort loading, and so it never reaches `WinMain`.

I guess we need to set a reference to Outpost2.exe so it's loaded by the OS loader before op2ext.dll's `DllMain` runs, or we need to delay both, so `op2ext.dll`'s `DllMain` runs after we can call `LoadLibrary` on Outpost2.exe.

----

This all got me thinking about our source code organization. We have a unit test executable project for the static library. Perhaps we should add one for the DLL.

**Comment by Brett208** [comment]
Well, I intended this issue to just be about small updates to the TestModule to keep it relevant. I think the long term discussion on an automated cross-dll boundary test suite is in issue #19, Automate Tests.

I'd like to close the issue when the updates are made, so maybe better to consolidate the longer term effort there.

If you think this automated cross-dll boundary test is imminent I suppose this issue may become obsolete.

-Brett

**Comment by DanRStevens** [comment]
Good point. I'm getting overly excited and distracted again. I'll stick to the other issue for the grandiose thoughts.

I'm not sure about imminent, but we could probably get something going within the next week or so. My recent test progressed quicker than expected. There was much less project setup required than I expected. I think I mostly just have to figure out how to get both modules loaded in the right order.

Your proposed changes here might still be relevant. I guess I'm not actually certain about all of what we need in terms of module testing and reporting.
