### ISSUE TITLE
When debugger attached, log file is not created at root Outpost2 directory

### ISSUE THREAD

**Issue by Brett208** [OutpostUniverse/op2ext#36]
When debugging with Visual Studio, the log file will no longer be created in the same directory as Outpost 2, but instead in the directory where the IDE project file is located.

I think proper behaviour would be to still create the log file in the Outpost 2 directory? This is the same issue that NetFix has when it creates its log file.

**Comment by DanRStevens** [comment]
It's probably just creating the log file using a filename, without a path component. That will cause it to appear in the current working directory. When launching from the Visual Studio IDE, the current working directory will be set to the Visual Studio project folder, rather than the game folder.

We should determine the game folder, and prepend that to the log filename.
