### ISSUE TITLE
strncopy_s cannot take 0 for bufferSize

### ISSUE THREAD

**Issue by Brett208** [OutpostUniverse/op2ext#43]
According to Microsoft's documentation, passing a destSize must be greater than 0. https://docs.microsoft.com/en-us/cpp/c-runtime-library/reference/strcpy-s-wcscpy-s-mbscpy-s?view=vs-2017

In order to support a paradigm of passing a destSize of 0 to get the actual required buffer size, I recommend we update to the function below. (Add a check for 0 up front).

```C++
size_t CopyStdStringIntoCharBuffer(const std::string& stringToCopy, char* buffer, size_t bufferSize)
{
	// Buffer must be one character larger than std::string since std::string does not include the null terminator.
	if (bufferSize == 0) {
		return stringToCopy.size() + 1;
	}

	strcpy_s(buffer, bufferSize, stringToCopy.c_str());

	if (bufferSize > stringToCopy.size()) {
		return 0;
	}

	return stringToCopy.size() + 1;
}
```

**Comment by DanRStevens** [comment]
For context, the original code in question is:
https://github.com/OutpostUniverse/op2ext/blob/5d0049563b62dc7e71c54bd63104e1b07f8d5039/op2ext.cpp#L32-L42

We should probably just move that utility method to the top of the file, rather than forward declare it. It should probably be separated from the exported methods anyway.

----

Due to all the "secure" string variants, with different compiler support, and different warning messages between them, I think I'd like to stay away from these updated C-style methods as much as possible. Perhaps we can use `std::string` methods directly here.

This was interesting:
https://stackoverflow.com/questions/10903181/copying-from-a-stdstring-to-a-char-array-and-null-terminating-the-result

In particular, look at the answer that suggests:
```cpp
inline void CopyAndNullTerminate(const std::string& source, char* dest, size_t dest_size)
{
    dest[source.copy(dest, dest_size-1)] = 0;
}
```

Relevant documentation:
https://en.cppreference.com/w/cpp/string/basic_string/copy
