### ISSUE TITLE
Create an include directory

### ISSUE THREAD

**Issue by Brett208** [OutpostUniverse/op2ext#44]
Should we move op2ext.h to an include directory? It is our only public header for use outside the dll.

**Comment by DanRStevens** [comment]
I'm fine with that. It might make it stand out better. It's also nicely standalone, as it doesn't depend on any other headers in the project.

Are you proposing splitting that repository into `src/` and `include/` folders?

**Comment by Brett208** [comment]
TestModule is specifically designed to test calling the op2ext.h external functions from a separate module. I think this will still be a valid need separate from a gtest project? It is how I verify calls make it to/from op2ext to a ini or console module. If we can accomplish both from one project, that would be fine I guess.

Some of the specific tests in TestModule could maybe be moved into gtest. Would have to look.

Happy with the SampleModules name.

We should remove the submodules folder and just have Outpost2DLL as a subfolder of op2ext. This would align better with the other project structures. It also could be confusing with op2ext already talking about modules to also have a git submodules folder.

**Comment by DanRStevens** [comment]
Agreed about removing the submodules folder and including Outpost2DLL as a direct subfolder.

I originally left that part out because I didn't want muddy up this issue too much. Though it seems my other suggestions were more contentious.

You're probably right about needing some kind of independent test module.

From my cursory examination of the code, I think many of the tests can be done in a normal Google Test unit test project. Probably not all of them though. We can defer on the parts we're not clear on yet.

**Comment by Brett208** [comment]
For now, I'll create a test project that uses gtest and the TestModule project alone. This will let us write the unit tests to close out PR #46. We can sort out which tests move over or what to do with TestModule later.

-Brett

**Comment by DanRStevens** [comment]
I was just looking back at this, and the new project structure. Most of the header files were moved to the `srcStatic/` folder. The `srcDLL/` folder only has two header files:
```
op2ext.h
resource.h
```

Is it still worth it to split `op2ext.h` into it's own folder? I'm kind of thinking no.

**Comment by Brett208** [comment]
I think the standard practice is to list the folder containing the external header in the additional includes section of the project file. In this case, it would bring both op2ext.h and resource.h into scope. resource.h is a standard name for the resource header used by MSVC. There might be room for avoiding some sort of collision if both projects contain resource.h by not bringing it into scope. 

There are rules on which header is pulled first. So I think a resource.h contained in the same directory as the project file would take priority, but no guarantee other projects will place their resource header in this manner. And it isn't something I would want to have to reason about.

We could rename the resource file to op2extResource.h or something else, but I sort of feel like using an include directory is cleaner. It also allows pushing more header files into the dll project in the future if needed without worrying about collisions from other projects if the name is generic.

-Brett

**Comment by DanRStevens** [comment]
You might be right. Both about the potential for name collisions, and likely also about the name resolution and priority order favoring the header from the current project.

I don't want to rename the resource file. That seems like a bit of a hack that just moves the problem around without really solving it.

----

One question on my mind, is if we should put the `include/` folder within the DLL project folder, or at the level above it in the solution folder. I sort of feel like it's more clean to place the folder/header within the project folder. Something about referencing source files with `../` seems wrong. I don't mind project references using `../` to reference other projects in the same solution so much, but it feels messy when used for source files.

----

How about this. I think my main apprehension right now, is trying to get the details right, and not breaking either the project files, nor the Linux makefile. That's been a repeated issue the last few days, and I'm feeling a little blinded by not having good CI support. Let's say we first prioritize getting CI unit testing working for both platforms, then look into adding the include directory.

**Comment by DanRStevens** [comment]
I was just thinking back to this issue. I think one of my apprehensions about splitting off an `include/` folder, is it separates the source code in `op2ext.cpp` from it's associated header file `op2ext.h`. It's nice when associated source and header files are in the same folder.

What if we handled this as part of the build and packaging? We could have the zip package bundle `op2ext.h` into the same archive as `op2ext.dll`. That could solve the issue for binary packages.

Alternatively, or as part of the above, the build process could copy `op2ext.h` into an `include/` folder along with the other outputs in the build folder. This could make it easier to package things in a zip file, as above. It could also provide a nice solution when a repository is used as a Git submodule. Such a setup would likely build dependent submodule first, which would establish the `include/` folder as part of the build.

Referencing the `include/` folder might be a bit icky though if it's buried under the build folder along with all the intermediate files. Maybe we could symlink just the final outputs to an `output/` folder right off the repository root. I suggest a symlink rather than an alternate output folder, as changing the active configuration could allow for very quick swap out of the symlinks without have to recompile anything.

**Comment by Brett208** [comment]
I would prefer to just close the issue at this point. I don't like the idea of adding mildy complex copy/scripting to simulate the folder structure during compilation when we can just leave well enough alone and not complicated. 

I would still support putting it in an include directory, but since you have remained apprehensive about it for so many months, lets just close and move on as it isn't really a big deal to me.

**Comment by DanRStevens** [comment]
Alright, I guess we'll close this for now. We can always re-open it later.
