### ISSUE TITLE
Rename external log function

### ISSUE THREAD

**Issue by Brett208** [OutpostUniverse/op2ext#59]
Since the C ABI does not support namespaces, I feel like naming a function log is a little irresponsible, as this has a high chance of interfering with a local function name in another dll.

Perhaps OP2extLog?

This is a breaking API change, but we are young enough into the log function that I doubt anyone else is using it yet or would have difficulty with the minor change since they are actively developing if there is an unknown project.

**Comment by DanRStevens** [comment]
What happens if the `#include "op2ext.h"` line is wrapped in a namespace? Does it still link correctly? I think it would. I've seen that method used before for C headers being imported by C++ projects. I think that would allow people to add the imported names to a namespace of their choosing.

In the above works, I think that would be sufficient. Plus I'd like to avoid an overly awful or long name for logging. Additionally, if we want consistent logging, maybe we should sort of actively discourage people from using their own `Log` function. :wink:

**Comment by Brett208** [comment]
Good idea about the namespace wrapping. Looks like we proved it in NetFixClient. That actually worked pretty well and think it is a fine solution for C++ applications.

The namespace wrapping would apply if someone actually decided to write a module in C, which I think is technically possible. In that case I don't think it would be unreasonable for them to segregate logging through op2ext with their own header and want the Log function name to be available. Maybe not worth worrying about because it would make the interface more clunky and there hasn't been an appetite for anyone to work in C on a module. 

Glad this was solved with the namespace wrapping.
