### ISSUE TITLE
Allow for verbose logging

### ISSUE THREAD

**Issue by Brett208** [OutpostUniverse/op2ext#64]
What sort of strategy do we want for allowing verbose/diagnostic logging? We can either support different logging details at the per module level or overall for all modules and op2ext.

We could add a property to the .ini file

```
[Game]
Logging=Verbose
```

I think for now a Default and Verbose option would be sufficient.

We could then add a function to op2ext.h:

```C++
enum LoggingLevel {
    Default,
    Verbose
}

LoggingLevel GetLoggingLevel()
```

The module would call GetLoggingLevel on initialization and record the value. It would then be up to the module to determine when a message met the fetched requirement.

---

Another solution would be for each module to check its section of the .ini file for logging verbosity. This would give more fine grained control (one module could be verbose, and one default). However Console modules would not be able to support verbosity through the .ini file since they do not use it. They could pull a global setting through op2ext's public interface though.

**Comment by DanRStevens** [comment]
I have no idea. I've thought about this. I think it's an issue I want to put off for now.

I think one reason why I want to put it off, is I sometimes feel it may be the wrong question. Effectively we are trying to decide up front what and how much should be logged. But we leave it adjustable because we don't actually know, and might need to change it. So the real question is why would we need to change the logging level. If we know that, we may be able to develop a better more automated logging system that logs exactly what is needed, when it is needed.

For instance, if NetFix is detecting connection problems, it might be more verbose about logging connection attempts or peer info. The decision might not be based on an ini file setting, but rather detecting some runtime anomaly.

**Comment by Brett208** [comment]
I think there is room to add logs to specifically trace debugging. 

Maybe a better approach is to play with how much is logged internal to NetFixClient's project for now and if it makes sense to have verbose / default. Once that is fleshed out, we can revisit whether this is beneficial?

**Comment by DanRStevens** [comment]
Thought maybe I'd leave a link to this, in case it was interesting:
https://github.com/gabime/spdlog

I came across it earlier today in a post about recommended C++ development tools, which listed that library for logging. It seems to support a few logging levels, with output adjustable at runtime. One particularly nice feature is the format strings that it allows. That could make formatting log messages much easier.

Also of curious note, is the network logger. That could potentially come in handy with NetFixClient when debugging connection problems between multiple clients. It might be possible to collect information from each client about how they see each other client. The server should already have most of the connection information, but due to differences in routers, there may be some discrepancies with port numbers.

**Comment by DanRStevens** [comment]
I was just looking back at this. If we were to export the method `LoggingLevel GetLoggingLevel()`, then we'd be pushing off responsibility for implementing logging verbosity to the client DLLs. That makes it less likely it would be used.

Perhaps easier from a module developer's perspective, is if we offered multiple logging functions:
```
Log(char* message); // Normal logging
LogError(char* message); // Very serious error, maybe with a popup
LogDebug(char* message); // For really verbose stuff that may not be so interesting
```

It would be much easier for the model designer to choose the level of importance of their message that way, and then have op2ext implement the mechanism for what gets logged, or where it gets logged to.

----

Still though, I wonder if this issue might be a distraction from the real problem, which is deciding which information is relevant and should be presented.

**Comment by Brett208** [comment]
Oh yeah, I like that idea better. Have the external DLLs send different levels of logging and based on op2ext's ini settings determine if it is logged or not. It reduces the overhead of integrating with op2ext.

**Comment by DanRStevens** [comment]
Tagging Issue #170 as currently blocking this issue.
