### ISSUE TITLE
Add tests for IniModules

### ISSUE THREAD

**Issue by Brett208** [OutpostUniverse/op2ext#76]
Currently, cannot test past having an empty/missing .ini file.

I think there are two choices here:
1. Dynamically try to write/update a test.ini file to pull values from during testing
2. Extract parsing the .ini file out of IniModuleLoader using Dependency Injection. Instead pass the results of parsing the .ini file into IniModuleLoader, allowing dummy settings to be passed in without actually reading a .ini file.

Dynamically re-writing the .ini file increases the amount of code tested as it also makes sure we properly read the ini file. There are some technical hurdles in that I don't know how easy it will be to write/rewrite the .ini file during unit tests. I also don't know how the appveyor automated build would respond to this.

Using dependency injection seems a little easier to implement from a technical perspective. I also like that it separates the code base into smaller parts.

**Comment by DanRStevens** [comment]
3. Pass an IniFile object to the IniModuleLoader constructor. When testing, an IniFileMock object can be passed instead that returns a set of pre-programmed responses. This would require defining an IniFile interface, which passed objects must adhere to, and reworking internal ini file access to go through the interface. The IniFile interface would need to support functionality similar to `GetOP2PrivateProfileString`, and optionally could be extended further to restrict access to a specific IniSection, with similar functionality but fewer parameters.

**Comment by DanRStevens** [comment]
Not really related to #131, but the Google Mock technique presented there may apply here.

**Comment by Brett208** [comment]
Since the ini module loader no longer exists, I renamed this issue. The heart of being able to test an ini module still exists though.

**Comment by Brett208** [comment]
Thanks to @DanRStevens' work with creating an IniFile abstraction and the improved ModuleLoader over IniModule, we are closer to testing. The next problem is not having a DLL to test against.

Can we place an empty DLL in the test directory to use in testing? Not sure if the mingw compiler can read a DLL formed via MSVC compilation. 

Another option would be to strip out portions of TestModule that are now tested using TestDll. Then we could compile TestModule as a DLL before running the test code and use it for IniModule testing.

I'm not sure if GoogleMock can be applied here. Frankly I'm not knowledgeable about mocking at all.

**Comment by DanRStevens** [comment]
Mingw can compile DLLs, so we can produce test modules on Linux from source code. The makefile is configured so it can build the TestModule project. I've used it a few times from Linux to do some manual testing.

What we want to do here doesn't really fall in the realm of unit tests though. This would be a higher level of test, which involves compiling multiple projects and integrating the results. Ideally I would like to add tests to cover cases like this, though those tests will likely be outside of the current test projects.

----

It may be worth striping down TestModule a bit to focus on areas not covered by the testDll project. Some of the TestModule code was more or less ported to the testDll project, though I never removed the source from TestModule.

----

I feel like the focus of this issue is not quite so clear anymore. It seems like it was originally focused on checking proper handling and error reporting for various INI file settings. I think we may have largely handled that already. The remaining untested case is testing with actual real modules, which falls outside the realm of unit tests. I think maybe we should close this issue as finished and start a new issue for end-to-end testing of INI modules.
