### ISSUE TITLE
Error in op2ext TestModule in function TestGetConsoleModuleDirectory

### ISSUE THREAD

**Issue by Brett208** [OutpostUniverse/op2ext#8]
When loading the test console module, MSVC seems to be reporting an error occurs when the command free() from below is run. Not sure what I'm doing wrong to cause this.

``` C++
// GetCurrentModDir only returns the directory of a module loaded through the console switch /loadmod
void TestGetConsoleModuleDirectory()
{
	char* moduleDirectory = GetCurrentModDir();
	std::string modDirectoryReport("GetCurrentModDir reports: " + std::string(moduleDirectory) + "\n");
	OutputDebugString(modDirectoryReport.c_str());

	free(moduleDirectory);
}
```

**Comment by DanRStevens** [comment]
The error is due to mixing of memory allocation routines, which is undefined behaviour. The `new[]` should be paired with a `delete[]`. This is a C++ interface though. If we want to stick to a C interface, we should use `malloc` instead of `new`.

`malloc`/`free`  (C)
`new`/`delete`  (C++, single object pointer)
`new[]`/`delete[]` (C++, array object pointer)

I recommend updating the following line to use `malloc`:
https://github.com/OutpostUniverse/op2ext/blob/babc7f34a4417219dde5a4ae708b742678607c61/op2ext.cpp#L50

**Comment by Brett208** [comment]
I'll take a stab at fixing this in the near future. See Branch #9 for detailed messages on what needs to happen. Will plan to open a new branch.

-Brett
