### ISSUE TITLE
Switch to path::generic_string

### ISSUE THREAD

**Issue by Brett208** [OutpostUniverse/op2ext#86]
Do we want to switch calls in op2ext from path::string to path::generic_string?

**Comment by DanRStevens** [comment]
I was thinking about that. I didn't largely because it's a Windows only library, and because there were already some uses of `.string()`.

----

I just tried it now, and I'm getting undefined references to the `.generic_string()` method at link time. I'm uncertain of the cause. Using just `.string()` seems to work.

**Comment by Brett208** [comment]
OK, thanks for investigating. We can always change it later if we change our minds. Good point about a Windows (+Wine) specific project.
