### ISSUE TITLE
MSVC reports Debug Assertion when calling free

### ISSUE THREAD

**Issue by Brett208** [OutpostUniverse/op2ext#88]
When using the TestModule, the following debug assertion is thrown by Visual Studio. Only when compiled in debug mode. It occurs even if switched to the delete keyword instead of free. (line 56 below)

<img width="625" alt="DebugAssertion" src="https://user-images.githubusercontent.com/15183337/56843786-f99f3880-6873-11e9-9853-e08156dd0e31.png">

I'm at a bit of a loss as to why this is happening.

**Comment by DanRStevens** [comment]
Because you're crossing the module boundary. The allocation is from op2ext, but the free is from the library. They each have their own heaps, so you're trying to free an object from a different heap than it was allocated on.

Usually this is solved by providing paired allocation / deallocation functions. In this case, op2ext would need to provide a method to free the returned memory.

I believe this is where we got into that discussion about pairing `new` / `delete` (C++), or `malloc` / `free` (C), and not mixing between the two. I believe we decided not to fix that because it was also broken due to the module boundary crossing.

**Comment by Brett208** [comment]
Right, thanks for reminding me. I'll add a comment to the code base so I remember next time. I wish I knew how to silence Debug Assertions when needed.

-Brett

**Comment by DanRStevens** [comment]
You can conditionally disable the test for debug builds. Effectively any code using those methods is broken, including test code. They just might appear to work under the right circumstances.

Side note: If you have a paired free function, you can use either `malloc` or `new`, so long as the paired free function uses the corresponding `free` or `delete[]` (it's an array of `char`, so use the vector delete).

If we want to still support the old deprecated method, perhaps we should add a new free method. That way we can at least write proper test code for the old method. It doesn't fix old compiled modules that we have no source for, but it can at least allow for proper testing.

**Comment by Brett208** [comment]
It is tough for me to justify adding a deprecated function to allow testing an already deprecated function to the public API.

**Comment by DanRStevens** [comment]
My only other suggestion then is to not test the deprecated methods.
