### ISSUE TITLE
Strip directory separators when forming ConsoleModuleName

### ISSUE THREAD

**Issue by Brett208** [OutpostUniverse/op2ext#93]
The console module name is formed from the /loadmod argument. This could be passed a directory with different path specific decorations that should be stripped to allow accepting a wider range of options without undefined behaviour within op2ext.

From @DanRStevens:

In terms of automatically handling conversions of weird paths with ".", "..", and normalizing trailing slash, perhaps the following methods may be helpful:

- https://en.cppreference.com/w/cpp/filesystem/canonical
- https://en.cppreference.com/w/cpp/filesystem/relative
- https://en.cppreference.com/w/cpp/filesystem/path/lexically_normal

These methods should provide a way to normalize paths that use "./" or "../". Some of them may also normalize use of symbolic links (which maybe we do or don't want to do). They will probably also help normalize trailing slash.

Looking at the first two, I think what you might want is fs::relative(moduleFolderPath, executableFolder), with any trailing slash stripped (which I think might be the default behavior).

Looking at the last method, you might use moduleFolderPath.lexically_relative(executableFolder). I believe the difference is the "lexical" method works on the path string alone, without ever checking the filesystem, and hence would not be bothered by path elements that don't exist and would not be able to resolve symbolic links.

**Comment by DanRStevens** [comment]
Tagging PR #91 as the source of the discussion that led to this issue.

Re-reading the discussion, it seems to suggest an approach where we allow the user to specify console modules by using a path to the folder, in whatever manner they choose, and then normalize it to a well known form. The normalized name allows for things such as detecting duplicate module names.

In contrast, the discussion does not seem to suggest locking down the user supplied portion so they can only specify the module name in one well known format.

There appears to be no restriction on multiple levels of subfolders to reach the module folder. Currently, I see no reason to impose an artificial restriction such as a single folder level. If nested folders are used, the whole relative path, including any directory separators, will become the module name.

**Comment by DanRStevens** [comment]
It seems the `<experimental/filesystem>` library included with Mingw does not include:
`relative`, `path::lexically_normal`, `path::lexically_relative`

This leaves only `canonical` for transforming and normalizing paths.

Note that `canonical` throws errors for paths that don't exist.

The `canonical` method does not take a base path, like the relative methods do, so paths would be absolute, rather than relative to some fixed directory such as the game directory.

**Comment by DanRStevens** [comment]
After some thought, I'm wondering if this is something we need to fix, or if we should perhaps close this as a non-issue.

It's not necessarily wrong to load the same module twice, provided each instance has a separate name. Different paths to the same place would produce a different name.

```
# User trying to be clever and load a module 3 times
outpost2.exe /loadmod modName /loadmod ./modName /loadmod ././modName
```

There is of course some potential danger in that two copies of a module might try to patch the same code twice. However, the same problem exists between two different modules. Two different modules might still try to patch the same section of code twice. Protecting against this is more up to the robustness of the modules themselves, rather than the module loader.

```
# Potentially conflicting modules
outpost2.exe /loadmod ColorMod1 /loadmod ColorMod2
```

Further, there is nothing stopping a user from making two copies of the same module, into different folders, and loading them that way.

```
# Actually all the same module
outpost2.exe /loadmod modName1 /loadmod modName2 /loadmod modName3
```

I think we're trying to be overly clever by trying to detect and prevent this.

PEBKAC :wink:
