### ISSUE TITLE
Handling modal dialog warnings during unit tests

### ISSUE THREAD

**Issue by Brett208** [OutpostUniverse/op2ext#96]
On a local branch, I used dependency injection to expand the testable portions of the ConsoleModuleLoader.

I end up having to click through a decent number of pop-up windows as the tests run. While this is okay for actual use as the user will want to know when the module loader fails in various ways, it doesn't work well for unit testing. 

I don't think we can automate the tests via appveyor because appveyor will not know how to click OK on the dialogs. (I'm not sure the dialogs can even render since it is a command line?).

Since all modal dialogs for warnings are passed through the function PostErrorMessage, I was thinking we could somehow add a way to turn off modal dialogs in the function based on whether op2ext-static is supporting unit tests or a dll build. 

```C++
void PostErrorMessage(std::string sourceFilename, long lineInSourceCode, std::string errorMessage)
{
	const std::string formattedMessage = sourceFilename + ", Line: " + std::to_string(lineInSourceCode) + ": " + errorMessage;
	logger.Log(formattedMessage);
	MessageBoxA(nullptr, formattedMessage.c_str(), "Outpost 2 Error", MB_ICONERROR);
}
```

I had thought maybe a preprocessor directive called TestEnvironment, but I don't know how you could set this for the DLL build and the test build separatley, as it would probably require recompiling.

Perhaps a non-compiling boolean variable called TestEnvironment. It could be set to true during initialization of the test environment and wouldn't be available outside of a static compilation unit (since it would not be marked for export across module boundaries).

Maybe there is a better solution I hadn't thought of though.

-Brett

**Comment by DanRStevens** [comment]
Ahh yes, classic testing problem.

Using a runtime environment detection is probably much better than a compile time change. You could potentially look for an environment variable that can be set during testing to avoid creating the popup boxes. If you want fewer deviations between testing and actual release, it may be possible to automate clicking of the close button. It's a bit ugly, but it can be done, and ensures you're testing what people will actually experience in the actual release. It may help knowing the control ID of the close button, as you could target the click for the button, rather than just some (x, y) coordinate.

I suspect AppVeyor will have a local graphical environment, at least in the virtual sense, even if there is no monitor attached to their servers. In particular, you can login to a paused AppVeyor build through remote desktop and use Visual Studio on the build instance to debug CI problems.
